// geneList object
const geneList = {
  bases: [
    ["black", /(B|b)(B|b)/],
    ["red", /(O|o)(O|o)/],
  ],
  marksMods: {
    common: [
      ["agouti", "Ag"],
      ["bicolored", "Bi"],
      ["braided-tabby", "BrT"],
      ["broken-tabby", "BroT"],
      ["capped", "Cp"],
      ["colorpointed", "Cpt"],
      ["collared", "Col"],
      ["cream", "Cr"],
      ["freckled", "Fr"],
      ["gradient", "Gra"],
      ["hooded", "Hd"],
      ["mackerel-tabby", "McT"],
      ["masked", "Msk"],
      ["mitted", "Mt"],
      ["pigeon", "Pg"],
      ["saddled", "Sd"],
      ["seal", "Se"],
      ["sheeted", "She"],
      ["shoes", "Sh"],
      ["ticked-tabby", "TcT"],
      ["tuxedoy", "Tx"],
    ],
    uncommon: [
      ["badger", "Bdg"],
      ["banded", "Bn"],
      ["blotched-tabby", "BlT"],
      ["cheetah", "Cht"],
      ["colorpatched", "Cpa"],
      ["doubled", "Db"],
      ["fawn", "Fw"],
      ["fish-scales", "Sc"],
      ["jay", "J"],
      ["merle", "M"],
      ["ocelot", "Oc"],
      ["owl", "Ow"],
      ["panda", "Pnd"],
      ["pinstriped-tabby", "PsT"],
      ["quail", "Qu"],
      ["sepia", "Sep"],
      ["serval", "Srv"],
      ["shaded", "Shd"],
      ["skunk", "Sk"],
      ["speckled-tabby", "SpT"],
      ["spotted-tabby", "SpoT"],
      ["van", "Vn"],
    ],
    rare: [
      ["brindle", "Bri"],
      ["caribou", "Car"],
      ["clouded", "Clo"],
      ["gazelle", "Gz"],
      ["kudo", "Kd"],
      ["marbled", "Mb"],
      ["monarch", "Mon"],
      ["peafowl", "Pf"],
      ["python", "Py"],
      ["rosette", "Ros"],
      ["silvered", "Slv"],
      ["smokey-tabby", "SmT"],
      ["sooty", "St"],
      ["tortoise", "To"],
      ["tweed", "Tw"],
      ["wildebeest", "W"],
      ["wolf", "Wo"],
      ["zebra", "Zb"],
    ],
    ultraRare: [
      ["sand", "Snd"],
      ["volcanic", "V"],
    ],
    legendary: [
      ["aura", "Au"],
      ["opaline", "Op"],
    ],
  },
  // split markings / modifiers version
  // markings: {
  //   common: [
  //     ["bicolored", "Bi"],
  //     ["braided-tabby", "BrT"],
  //     ["broken-tabby", "BroT"],
  //     ["capped", "Cp"],
  //     ["collared", "Col"],
  //     ["freckled", "Fr"],
  //     ["hooded", "Hd"],
  //     ["mackerel-tabby", "McT"],
  //     ["masked", "Msk"],
  //     ["mitted", "Mt"],
  //     ["pigeon", "Pg"],
  //     ["seal", "Se"],
  //     ["sheeted", "She"],
  //     ["shoes", "Sh"],
  //     ["ticked-tabby", "TcT"],
  //     ["tuxedoy", "Tx"],
  //   ],
  //   uncommon: [
  //     ["badger", "Bdg"],
  //     ["banded", "Bn"],
  //     ["blotched-tabby", "BlT"],
  //     ["cheetah", "Cht"],
  //     ["colorpatched", "Cpa"],
  //     ["fawn", "Fw"],
  //     ["fish-scales", "Sc"],
  //     ["jay", "J"],
  //     ["ocelot", "Oc"],
  //     ["owl", "Ow"],
  //     ["panda", "Pnd"],
  //     ["pinstriped-tabby", "PsT"],
  //     ["quail", "Qu"],
  //     ["serval", "Srv"],
  //     ["skunk", "Sk"],
  //     ["speckled-tabby", "SpT"],
  //     ["spotted-tabby", "SpoT"],
  //     ["van", "Vn"],
  //   ],
  //   rare: [
  //     ["clouded", "Clo"],
  //     ["gazelle", "Gz"],
  //     ["kudo", "Kd"],
  //     ["monarch", "Mon"],
  //     ["peafowl", "Pf"],
  //     ["python", "Py"],
  //     ["rosette", "Ros"],
  //     ["smokey-tabby", "SmT"],
  //     ["sooty", "St"],
  //     ["tortoise", "To"],
  //     ["tweed", "Tw"],
  //     ["wildebeest", "W"],
  //     ["wolf", "Wo"],
  //     ["zebra", "Zb"],
  //   ],
  //   ultraRare: [],
  //   legendary: [],
  // },
  // modifiers: {
  //   common: [
  //     ["agouti", "Ag"],
  //     ["colorpointed", "Cpt"],
  //     ["cream", "Cr"],
  //     ["gradient", "Gra"],
  //     ["saddled", "Sd"],
  //   ],
  //   uncommon: [
  //     ["doubled", "Db"],
  //     ["merle", "M"],
  //     ["sepia", "Sep"],
  //     ["shaded", "Shd"],
  //   ],
  //   rare: [
  //     ["brindle", "Bri"],
  //     ["caribou", "Car"],
  //     ["marbled", "Mb"],
  //     ["silvered", "Slv"],
  //   ],
  //   ultraRare: [
  //     ["sand", "Snd"],
  //     ["volcanic", "V"],
  //   ],
  //   legendary: [
  //     ["aura", "Au"],
  //     ["opaline", "Op"],
  //   ],
  // },
};
